Repository ComputeCanada/magic_castle, pull requests merged in 2024-01, with the labels that each got.

#277 Fix version of faraday* gems in cloud-init
  common/configuration/puppet.yaml
Labels: bug

#278 Add documentation about start_timeout and SLURM version for autoscaling
  docs/terraform_cloud.md
Labels: documentation

#281 Improve var.software_stack flexibility and documentation
  common/variables.tf
  docs/README.md
Labels: documentation, enhancement

#284 Yaml validation on hierada
  common/variables.tf
Labels: enhancement
